### ISSUE TITLE
PIP install dependency conflict

### ISSUE THREAD

**Issue by yvvijay121** [PolicyEngine/openfisca-us#296] opened 2021-11-21 18:13 UTC
OS: Windows 10
I'm having issues with installing `pathlib`, so this could be why.
Happened when attempting to install from git repository and locally.

```
ERROR: Cannot install OpenFisca-US because these package versions have conflicting dependencies.

The conflict is caused by:
    openfisca-us-data 0.1.3 depends on pathlib
    openfisca-us-data 0.1.2 depends on pathlib

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by nikhilwoodruff** [comment] 2021-11-21 19:48
Hmm, yeah the package definitely uses `pathlib` in a few places so probably unavoidable to install - could you share the issue with installing `pathlib`?

**Comment by yvvijay121** [comment] 2021-11-21 19:57
Yes, here's the error statement when attempting to install `pathlib`:
```
ERROR: Could not find a version that satisfies the requirement pathlib (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.97, 1.0, 1.0.1)
ERROR: No matching distribution found for pathlib
```
If you need more information, I'll also add the complete output of `pip install pathlib`.

**Comment by nikhilwoodruff** [comment] 2021-11-21 23:12
That'd be useful, thanks. Is it possible you could be using Python 2.7?

**Comment by yvvijay121** [comment] 2021-11-21 23:19
No, I've confirmed that I am using Python 3.8.1.

**Comment by nikhilwoodruff** [comment] 2021-11-23 11:09
OK, thanks - could you share the `pathlib` install error? That's probably the root cause here

**Comment by yvvijay121** [comment] 2021-11-24 00:22
Sure! Attached is a text file with the complete output after running `pip install pathlib`.
[pipoutput.txt](https://github.com/PolicyEngine/openfisca-us/files/7591731/pipoutput.txt)

**Comment by CrimsonOHara** [comment] 2021-11-28 16:10
I am facing the same issue.

**Comment by CrimsonOHara** [comment] 2021-11-28 16:34
I was able to solve it locally by building an egg of openfisca-us-data and then using it locally like this
```
    dependency_links=[
        # location to your egg file
        os.path.join(os.getcwd(), 'deps', 'openfisca_us_data-0.1.3-py3.9.egg'),
    ],
```

**Comment by nikhilwoodruff** [comment] 2021-11-28 17:04
Weird - OK though - seems like the general solution could be to use Python 3.7 (that's what we're testing on - sorry I hadn't mentioned this!).

**Comment by MaxGhenis** [comment] 2021-11-28 17:09
@yvvijay121 could you share your Python version? `python -V`

**Comment by yvvijay121** [comment] 2021-11-28 17:48
@MaxGhenis, I already shared my Python version; I am using Python 3.8.1.
```
PS C:\Programming_Projects\PolicyEngine\openfisca-us> python -V
Python 3.8.1
```

**Comment by MaxGhenis** [comment] 2022-01-08 16:16
Closing as we've confirmed that using Python 3.7 resolves the issue

**Closed by MaxGhenis** 2022-01-08 16:16 UTC
